// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj5vf2EdAeCo71gL-dEDwP_VLjPmnyi_g',
    appId: '1:129501588950:web:b11f88c7d022cf24e48877',
    messagingSenderId: '129501588950',
    projectId: 'pizza-90a0a',
    authDomain: 'pizza-90a0a.firebaseapp.com',
    storageBucket: 'pizza-90a0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCchnEc0dBDwVxD01DLKC_HaufPtdhZ-YA',
    appId: '1:129501588950:android:186b6119615861d5e48877',
    messagingSenderId: '129501588950',
    projectId: 'pizza-90a0a',
    storageBucket: 'pizza-90a0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCixBiZNJVFP6bXg0tRBFkT8u43jDCZgSA',
    appId: '1:129501588950:ios:bdcf51afc88638a6e48877',
    messagingSenderId: '129501588950',
    projectId: 'pizza-90a0a',
    storageBucket: 'pizza-90a0a.appspot.com',
    iosBundleId: 'com.example.pizzaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCixBiZNJVFP6bXg0tRBFkT8u43jDCZgSA',
    appId: '1:129501588950:ios:33e946a689be66bae48877',
    messagingSenderId: '129501588950',
    projectId: 'pizza-90a0a',
    storageBucket: 'pizza-90a0a.appspot.com',
    iosBundleId: 'com.example.pizzaapp.RunnerTests',
  );
}
